name: Test App

on:
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - '**.tsx?'
      - '**.jsx?'
      - '**.json'
      - '**.s?css'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Format check
        run: |
          npm run ts:check
          npm run stylelint:check
